@url = http://localhost:1234

### POST
POST {{url}}/
Content-Type: application/json

{
    "nombre": "pedro",
    "notas": [8, 9, 5]
}

### GET
GET {{url}}/

### GET
GET {{url}}/pedro

### PUT
PUT {{url}}/pedro
Content-Type: application/json

{
    "notas": [9, 8, 10]
}
